In [1]:
import numpy as np


In [2]:
#printing a random numbers

In [11]:
data = np.random.randint(1,10,15)

In [12]:
data

array([8, 2, 7, 9, 5, 7, 6, 3, 8, 5, 4, 4, 5, 5, 4])

In [13]:
data+2

array([10,  4,  9, 11,  7,  9,  8,  5, 10,  7,  6,  6,  7,  7,  6])

In [15]:
data-2

array([6, 0, 5, 7, 3, 5, 4, 1, 6, 3, 2, 2, 3, 3, 2])

In [16]:
data*2

array([16,  4, 14, 18, 10, 14, 12,  6, 16, 10,  8,  8, 10, 10,  8])

In [ ]:
# to printing a matrix form

In [17]:
data = np.random.randint(2,5,(6,4))

In [18]:
data

array([[2, 3, 4, 2],
       [2, 3, 3, 3],
       [4, 4, 2, 2],
       [4, 2, 3, 3],
       [3, 2, 3, 3],
       [2, 4, 2, 2]])

In [20]:
x=np.random.randint(2,3,(4,4))

In [21]:
x

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [23]:
y=np.random.randint(3,6,(4,4))

In [24]:
y

array([[3, 5, 5, 3],
       [5, 3, 5, 4],
       [5, 3, 3, 5],
       [4, 3, 5, 5]])

In [25]:
x+y

array([[5, 7, 7, 5],
       [7, 5, 7, 6],
       [7, 5, 5, 7],
       [6, 5, 7, 7]])

In [26]:
x-y

array([[-1, -3, -3, -1],
       [-3, -1, -3, -2],
       [-3, -1, -1, -3],
       [-2, -1, -3, -3]])

In [27]:
x*y

array([[ 6, 10, 10,  6],
       [10,  6, 10,  8],
       [10,  6,  6, 10],
       [ 8,  6, 10, 10]])

In [44]:
x=np.random.randint(10,30,(7,4))

In [45]:
x.shape

(7, 4)

In [49]:
data=np.random.randint(1,10,(3,3))

In [50]:
data

array([[3, 7, 9],
       [8, 9, 7],
       [1, 3, 3]])

In [51]:
data.argmax()

np.int64(2)

In [53]:
data.argmin()

np.int64(6)

In [54]:
data.sum(axis=0)

array([12, 19, 19])

In [55]:
data.sum(axis=1)

array([19, 24,  7])

In [ ]:
# mean,median

In [57]:
data.mean()

np.float64(5.555555555555555)

In [59]:
np.median(data)

np.float64(7.0)

In [ ]:
#to find mode we can us scipy as stats

In [74]:
import numpy as np
from scipy import  stats

In [68]:
data

array([[3, 7, 9],
       [8, 9, 7],
       [1, 3, 3]])

In [75]:
stats.mode(data)

ModeResult(mode=array([1, 3, 3]), count=array([1, 1, 1]))

In [48]:
x.cumsum()

array([ 11,  37,  62,  79,  95, 105, 130, 147, 166, 181, 192, 217, 232,
       246, 269, 288, 300, 311, 338, 365, 390, 413, 425, 442, 459, 485,
       511, 530])