In [1]:
import numpy as np


In [7]:
data = np.random.randint(1,5,(4,4))
data

array([[1, 3, 3, 4],
       [1, 1, 3, 3],
       [2, 2, 3, 3],
       [4, 2, 3, 1]])

In [8]:
data.sum()

np.int64(39)

In [9]:
data.sum(axis=0)

array([ 8,  8, 12, 11])

In [10]:
data.sum(axis=1)

array([11,  8, 10, 10])

In [12]:
data.max()

np.int64(4)

In [14]:
data.min()

np.int64(1)

In [15]:
data

array([[1, 3, 3, 4],
       [1, 1, 3, 3],
       [2, 2, 3, 3],
       [4, 2, 3, 1]])

In [16]:
data.min(axis=0).sum()

np.int64(6)

In [17]:
data.mean()

np.float64(2.4375)

In [20]:
np.median(data)

np.float64(3.0)

In [23]:
np.quantile(data,0.75)

np.float64(3.0)