In [1]:
import numpy as np

In [2]:
data = np.random.randint(1,20,(3,3))
data

array([[17,  6,  2],
       [ 4, 16,  8],
       [ 1,  1,  8]])

In [3]:
np.var(data)

np.float64(32.22222222222222)

In [4]:
np.median(data)

np.float64(6.0)

In [6]:
data.sum(axis=1)

array([25, 28, 10])

In [7]:
data.sum(axis=0)

array([22, 23, 18])